:PROPERTIES:
:ID:       e2302fd8-41ab-44f3-9db5-2888b28c198e
:END:
#+TITLE: AccessAuditBot
#+AUTHOR: Costin Dragoi
#+DATE: [2023-05-30 Tue]
#+FILETAGS: project clojure chatgpt
#+CATEGORY: private

* NEXT Working on AccessAuditBot :noexport:
:LOGBOOK:
- State "NEXT"       from "TODO"       [2023-05-30 Tue 18:11]
- State "TODO"       from              [2023-05-30 Tue 18:10]
:END:

* About

AccessAuditBot is a Telegram bot that utilizes the ChatGPT API to analyze Linux server logs and detect unauthorized access attempts. The bot alerts the user via Telegram notifications when potential security breaches are detected. The application is being tested and run on a Raspberry Pi 4 running Raspbian.

* Tools

This project is built using the following tools and frameworks:

- Clojure: A dynamic, general-purpose programming language that runs on the Java Virtual Machine.
- Telegrambot-lib: A Clojure library for building bots using the Telegram Bot API.
- OpenAI-Clojure: A Clojure library for integrating with the OpenAI API, used to leverage the capabilities of ChatGPT.
- Raspbian: The operating system running on the Raspberry Pi 4 where the program is tested.

* Development

** Prerequisites

To develop AccessAuditBot, you will need the following packages:

*** On Linux (Debian-based)

You can install the packages using *apt*:

#+BEGIN_SRC shell
sudo apt update
sudo apt install clojure
#+END_SRC

*** On macOS

You can install the packages using *Homebrew*:

#+BEGIN_SRC shell
brew update
brew install clojure
#+END_SRC

** Quickstart

To get started with the development, clone the repository and navigate into the directory:

#+BEGIN_SRC shell
git clone https://github.com/stindrago/access-audit-bot.git
cd access-audit-bot
#+END_SRC

** Setup

You need to setup your Telegram Bot Token and OpenAI API Key in the config file. You can do this by editing the *resources/config.edn* file in the root directory with the following lines:

#+BEGIN_SRC shell
{:openai-token "<your-telegram-bot-token>"
 :telegram-token "<your-openai-api-key>"}
#+END_SRC

** Deployment

Deployment instructions will be provided soon.

* License

AccessAuditBot is licensed under the [[./LICENSE][AGPL License]].
